export const colors = {
  baseBg: '#E5E5E5',
  bg: '#FFFFFF',
  errorBg: '#eb5a46',
  inputBg: '#fafbfc',
  inputBorder: '#dfe1e6',
  inputHoverBorder: '#4c9aff',
  baseButtonBg: '#cdd2d4',
  baseButtonHoverBg: '#c4c9cc',
  baseButtonActiveBg: '#b6bbbf',
  baseButtonColor: '#524e4e',
  secondaryBg: '#74b4cd',
  submitButtonBg: '#1390E5',
  submitButtonHoverBg: '#13a2E1',
  submitButtonActiveBg: '#1339E5',
};
